allowBuilds:
  lefthook: false
minimumReleaseAgeExclude:
  - lefthook-darwin-arm64@2.2.1
  - lefthook-darwin-x64@2.2.1
  - lefthook-freebsd-arm64@2.2.1
  - lefthook-freebsd-x64@2.2.1
  - lefthook-linux-arm64@2.2.1
  - lefthook-linux-x64@2.2.1
  - lefthook-openbsd-arm64@2.2.1
  - lefthook-openbsd-x64@2.2.1
  - lefthook-windows-arm64@2.2.1
  - lefthook-windows-x64@2.2.1
  - lefthook@2.2.1
